apiVersion: v1
data:
  enabled_plugins: |
    [rabbitmq_management
    ,rabbitmq_mqtt
    %% ,rabbitmq_auth_backend_http
    ,rabbitmq_web_mqtt
    ,rabbitmq_web_mqtt_examples].
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: enabled-plugins
